server.port=8081
spring.datasource.url=jdbc:postgresql://172.18.0.2:5432/orderdb
spring.datasource.username=postgres
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
