server.port=8081
spring.datasource.url=jdbc:postgresql://postgres-orders:5432/orderdb
spring.datasource.username=postgres
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
