server.port=8082
spring.datasource.url=jdbc:postgresql://postgres-payments:5432/paymentdb
spring.datasource.username=postgres
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
